package domain.controller;

public enum GameState {
    FIRST_ROAD, SECOND_ROAD, FIRST_SETTLEMENT, SECOND_SETTLEMENT, BUILD_SETTLEMENT, DEFAULT, BUILD_ROAD, UPGRADE_SETTLEMENT, TURN_START, ROAD_BUILDING_1, ROAD_BUILDING_2
}
