@startuml
'https://plantuml.com/class-diagram

+class RoadGraph {
}

+class Road {
}

RoadGraph --down>"*" Road

+class VertexGraph {
}

+class Vertex {
}

+class Port {
}

VertexGraph --down>"*" Vertex
VertexGraph --down>"*" Port

+class GameBoard {
}

+class Tile {
}

GameBoard --down>"*" Tile

+class DevelopmentCardDeck {
}

+class DevCard {
}

DevelopmentCardDeck --down>"*" DevCard

+class Game {
}

Game --down> GameBoard
Game --down> VertexGraph
Game --down> RoadGraph
Game --down> DevelopmentCardDeck

+class Player {
}

+class Hand {
}

Player --down> Hand

+class Controller {
}

Controller --down> Game
Controller --down>"*" Player

+class Bank {
}

@enduml